branch-defaults:
  aws:
    environment: Takeouttaxi-env
  master:
    environment: null
    group_suffix: null
environment-defaults:
  Takeouttaxi-env:
    branch: null
    repository: null
global:
  application_name: Custom Platform Builder
  branch: master
  default_ec2_keyname: Richardm2011
  default_platform: Ruby 2.6 (Puma)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application
