version: 0.2
phases:
 pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  install:
    runtime-versions:
    ruby: 2.6
    docker: 18
    commands:
    - npm install --global yarn 
    - npm install --global gatsby-cli
    - yarn 
    - gatsby build
    - aws s3 sync public s3://elasticbeanstalk-us-east-1-412285691131 --delete

    