version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
    - npm install --global yarn 
    - npm install 
    - yarn 
PRE_BUILD:
  artifacts:
    files:
      - '**/*'
    name: myname-$(date +%Y-%m-%d) 
 